# .github/workflows/build-and-push.yml

name: Build and Push Gotenberg Image to Docker Hub

# 触发条件：当有代码推送到 main 分支时，自动运行
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 服务器来执行任务
    steps:
      # 第1步：把您的代码仓库内容下载到服务器上
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第2步：登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 第3步：构建镜像并推送到 Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # 使用当前目录的 Dockerfile
          push: true # 确认执行推送操作
          # 【重要】请将这里的镜像名修改为您自己的！
          # 格式: 你的DockerHub用户名/自定义镜像名:标签
          tags: myliwh/gotenberg-with-fonts:1.0
